### ISSUE TITLE
Question regarding stability

### ISSUE THREAD

**Issue by atmosphere6619** [friends-of-freeswitch/switchio#67]
I've become very interested in this project over the past few days. I'm considering attempting to implement this into an existing freeswitch solution to add better functionality. Do you think this could be suitable for a production environment?

**Comment by goodboy** [comment]
Hey @atmosphere6619 I do think you would be fine using this in production but, of course, the project comes with no guarantees or warrants :wink:.

The project was originally built for stress testing production systems so it had to be at least as reliable as those systems under test.

I'd personally recommend introducing it in a staging environment first and maybe mirroring traffic to verify you can get the performance and reliability you desire.

**Comment by goodboy** [comment]
Anyone looking to report or follow up on this fee free to re-open.
